on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  repository_dispatch:
    types: [opened, deleted]

jobs:
  print_hi:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: echo "Hi"
